package executor_test

import (
	"fmt"
	"testing"

	"github.com/pingcap/tidb/pkg/testkit"
	"github.com/stretchr/testify/require"
)

func TestUpdateWithOnUpdateAndAutoGenerated__HABITAT(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewSteppedTestKit(t, store)
	tk.MustExec("use test")

	tk.MustExec(`
		CREATE TABLE cache (
			cache_key varchar(512) NOT NULL,
			updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			expired_at datetime GENERATED ALWAYS AS (if(expires > 0, date_add(updated_at, interval expires second), date_add(updated_at, interval 99 year))) VIRTUAL,
			expires int(11),
			PRIMARY KEY (cache_key) /*T![clustered_index] CLUSTERED */,
			KEY idx_c_on_expired_at (expired_at)
		)`)
	tk.MustExec("INSERT INTO cache(cache_key, expires) VALUES ('2001-01-01 11:11:11', 60) ON DUPLICATE KEY UPDATE expires = expires + 1")
	tk.MustExec("select sleep(1)")
	tk.MustExec("UPDATE cache SET expires = expires + 1 WHERE cache_key = '2001-01-01 11:11:11'")
	for _, enabled := range []bool{false, true} {
		tk.MustExec(fmt.Sprintf("set @@tidb_enable_fast_table_check = %v", enabled))
		tk.MustExec("admin check table cache")
	}

	rs1 := tk.MustQuery("select cache_key, expired_at from cache use index(idx_c_on_expired_at) order by cache_key")
	rs2 := tk.MustQuery("select cache_key, expired_at from cache use index() order by cache_key")
	require.True(t, rs1.Equal(rs2.Rows()))

	tk.MustExec(`
		CREATE TABLE ttime (
			id int,
			time1 datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			time2 datetime GENERATED ALWAYS AS (date_add(time1, interval 1 day)) VIRTUAL,
			time3 datetime GENERATED ALWAYS AS (date_add(time2, interval 1 day)) VIRTUAL,
			KEY idx (id, time2),
			KEY idx2 (time3)
		)`)

	tk.MustExec("INSERT INTO ttime SET id = 1")
	tk.MustExec("SELECT sleep(1)")
	tk.MustExec("UPDATE ttime SET id = 2")
	for _, enabled := range []bool{false, true} {
		tk.MustExec(fmt.Sprintf("set @@tidb_enable_fast_table_check = %v", enabled))
		tk.MustExec("admin check table ttime")
	}

	rs1 = tk.MustQuery("select time3 from ttime use index(idx2)")
	rs2 = tk.MustQuery("select time3 from ttime use index()")
	require.True(t, rs1.Equal(rs2.Rows()))

	rs1 = tk.MustQuery("select time2 from ttime use index(idx)")
	rs2 = tk.MustQuery("select time2 from ttime use index()")
	require.True(t, rs1.Equal(rs2.Rows()))
}
